# Change these first
owner: athere # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AtHere ShortURL Service
    url: https://athe.re/
  - name: AtHere Bookmark Service
    url: https://bookmark.family.im/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.athe.re
  # baseUrl: /your-repo-name
  name: AtHere Service Status Monitor
  introTitle: AtHere Service Status Monitor
  introMessage: Use **real-time** data from our [Github repository](https://github.com/koj-co/upptime) powered by open-source uptime monitor **Upptime** and **GitHub**.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
